### PR TITLE
added support for roborock.vacuum.s6

### PR DESCRIPTION
**Pull request by 0Bu**

### CODE REVIEW

**Comment by simonk83** [comment]
Great thanks, just came here to report it wasn't yet working

**Comment by simonk83** [comment]
Hmm, I added this manually but still getting:

Device ID: xxx
Model info: Unknown
Address: 192.168.1.168
Token: ???
Support: Unknown

**Comment by 0Bu** [comment]
Did you look at the changes of the pool request? What did you expect?

**Comment by simonk83** [comment]
> Did you look at the changes of the pool request? What did you expect?

This is the first time I'm using miio, and just want to get the token for use in HomeAssistant. So considering your pull request says it's adding support for the S6, I suppose I expected it to work.

**Comment by 0Bu** [comment]
RTM https://github.com/aholstenson/miio/blob/master/docs/management.md#getting-the-token-of-a-device

**Comment by andreypopov** [comment]
please, also add
roborock.vacuum.m1s

**Comment by andreypopov** [comment]
any news?

**Comment by 0Bu** [comment]
Hi andrey, feel free to create a new pull request. It seems to me that the project is dead.
Or ask @nicoh88 for support https://github.com/nicoh88/miio

**Pull request closed without merging**
