### PR TITLE
humidifier

### PR DESCRIPTION
**Pull request by ben423423n32j14e**

### CODE REVIEW

**Comment by aholstenson** [comment]
Thank you for this pull request. I'll create a quick implementation based on your findings so that the humidifier gets an easy to use API as well.

**Comment by aholstenson** [comment]
There is now a humidifier type in the `master` branch. Feel free to test if the exposed methods work with your device and either open issues or pull requests with things that do not work. I made one addition to the supported modes by adding `idle`, I'm not 100% that the humidifier supports it but as it's from Zhimi and the air purifier does I'm guessing the device is in that state when it is powered off.

If you know what `limit_hum`, `trans_level` and `cola` represents I'm very interested in adding in support for those properties as well.

**Comment by ben423423n32j14e** [comment]
Everything in the doc I submitted has been tested on my humidifier.

I just tested, idle, it doesn't exist.

**Comment by aholstenson** [comment]
Alright! I've removed the `idle` mode from the device implementation. Thanks again for your pull request!

**Pull request merged**
