### PR TITLE
Gateway control color and brightness

### PR DESCRIPTION
**Pull request by Gromina**
I hope other control commands (sound related) will work in the same manner. Just didn't have enough time to implement them

Code is based on
https://github.com/louisZL/lumi-gateway-local-api/blob/master/网关.md
https://github.com/octa22/org.openhab.binding.xiaomigateway/blob/master/src/main/java/org/openhab/binding/xiaomigateway/internal/XiaomiGatewayBinding.java
https://github.com/corbinmunce/domoticz/blob/master/hardware/XiaomiGateway.cpp

### CODE REVIEW

**Comment by aholstenson** [comment]
Thanks for the pull request! I've been trying to avoid using the local developer API for writes and instead map against the miIO-methods. There is a method called `set_rgb` that controls the color and brightness of the gateway. I've been ignoring that part of the gateway, but it really deserves proper support.

I added a first implementation using this method that uses the capability `brightness` and `color:rgb` which is the same as used by the `light`-type (for Yeelights). I'm currently a bit unsure if that actually belongs on the gateway or if the gateway should expose a virtual sub-device for its light functionality.

Here a few quick notes about the API:

* `setRGB(color)` takes either a string with a hex color (such as `#ff00aa`) or an object with the keys `red`, `green`, `blue` with values between 0 and 255.
* `setBrightness(brightness)` takes a value between 0 and 100 to indicate the brightness.

Does this implementation work for your use case?

**Comment by Gromina** [comment]
Will try it asap

**Comment by Gromina** [comment]
In overall it works.
Got an issue though.
```
			const rgb = 0x7f0000ff
			return this.call('set_rgb', [ rgb ]);
```
^ works fine
```
			const rgb = 0xff0000ff
			return this.call('set_rgb', [ rgb ]);
```
^ fails with


I believe the problem is somewhere in parameter type conversion inside set_rgb / call

` miio.device.[192.168.88.70] -> (3) {"id":2,"method":"set_rgb","params":[-65536]} +0ms
  miio.packet -> <Buffer 21 31 00 50 00 00 00 00 02 bb 64 a3 00 01 4e a0 16 5d 10 37 24 63 a9 ee d8 71 b4 b7 ec 8c 0e 66> +0ms
  miio.packet <- <Buffer 21 31 00 60 00 00 00 00 02 bb 64 a3 00 01 4e a0 9b 4f 00 53 a3 32 48 1d 66 7f 1c a3 d2 51 99 59> +7ms
  miio.device.[192.168.88.70] <- Message: `{"error":{"code":-5005,"message":"params error"},"id":2}` +0ms
(node:25960) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error
(node:25960) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Gromina** [comment]
Actually, the problem is in setBrightness itself. I gonna do other pull request

**Pull request closed without merging**
